FROM amazon/aws-cli

ARG USER=dev-user
ARG USER_ID=1000

# RUN yum install -y --disablerepo=amzn2-core* \
#    sudo \
#    git \
#    curl \ 
#    shadow-utils

# add dev-user
# RUN groupadd --gid $USER_GID $USERNAME \
#     && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -s $USER_SHELL\
#     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
#     && chmod 0440 /etc/sudoers.d/$USERNAME

